<?php

declare(strict_types=1);

namespace Click\Cms\Domain\Media;

use InvalidArgumentException;

/**
 * One item in the media library.
 *
 * `id` is the stable reference stored in content. It is generated by the CMS
 * rather than taken from the upload, so a page never depends on whatever a
 * browser happened to call the file, and two people uploading "photo.jpg"
 * cannot collide.
 *
 * The original filename is kept for display only.
 */
final class MediaItem
{
    /**
     * @param list<ImageSize> $variants Sizes actually generated for this item.
     */
    private function __construct(
        public readonly string $id,
        public readonly string $extension,
        public readonly string $mimeType,
        public readonly string $originalName,
        public readonly int $bytes,
        public readonly ?int $width,
        public readonly ?int $height,
        public readonly array $variants,
        public readonly string $alt,
        public readonly string $uploadedAt,
    ) {}

    /**
     * @param list<ImageSize> $variants
     */
    public static function create(
        string $id,
        string $extension,
        string $mimeType,
        string $originalName,
        int $bytes,
        ?int $width = null,
        ?int $height = null,
        array $variants = [],
        string $alt = '',
        ?string $uploadedAt = null,
    ): self {
        if (preg_match('/^[a-z0-9][a-z0-9-]*$/', $id) !== 1) {
            throw new InvalidArgumentException(
                'Media id must be lowercase letters, digits and dashes.'
            );
        }

        // Checked against the accepted set rather than merely for shape: "php"
        // is a well-formed lowercase extension, and a stored filename ending in
        // it should never be constructible even though media lives outside the
        // document root.
        if (!in_array($extension, UploadPolicy::acceptedExtensions(), true)) {
            throw new InvalidArgumentException(
                "Media extension \"{$extension}\" is not an accepted image type."
            );
        }

        return new self(
            id: $id,
            extension: $extension,
            mimeType: $mimeType,
            originalName: $originalName,
            bytes: $bytes,
            width: $width,
            height: $height,
            variants: $variants,
            alt: $alt,
            uploadedAt: $uploadedAt ?? gmdate('c'),
        );
    }

    /**
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        $variants = [];
        foreach ((array) ($row['variants'] ?? []) as $value) {
            $size = ImageSize::tryFrom((string) $value);
            if ($size !== null) {
                $variants[] = $size;
            }
        }

        return self::create(
            id: (string) ($row['id'] ?? ''),
            extension: (string) ($row['extension'] ?? ''),
            mimeType: (string) ($row['mimeType'] ?? 'application/octet-stream'),
            originalName: (string) ($row['originalName'] ?? ''),
            bytes: (int) ($row['bytes'] ?? 0),
            width: isset($row['width']) ? (int) $row['width'] : null,
            height: isset($row['height']) ? (int) $row['height'] : null,
            variants: $variants,
            alt: (string) ($row['alt'] ?? ''),
            uploadedAt: isset($row['uploadedAt']) ? (string) $row['uploadedAt'] : null,
        );
    }

    public function filename(): string
    {
        return $this->id . '.' . $this->extension;
    }

    public function isImage(): bool
    {
        return str_starts_with($this->mimeType, 'image/');
    }

    /**
     * Public URLs for the original and every generated variant.
     *
     * Returned as data rather than built in a template so a front end can put
     * the variants straight into a srcset without knowing the naming rule.
     *
     * @return array{original: string, variants: array<string, array{url: string, width: int}>}
     */
    public function urls(string $baseUrl = '/api/media/file'): array
    {
        $base = rtrim($baseUrl, '/');

        $variants = [];
        foreach ($this->variants as $size) {
            $variants[$size->value] = [
                'url' => $base . '/' . $size->filenameFor($this->id, $this->extension),
                'width' => $size->width(),
            ];
        }

        return [
            'original' => $base . '/' . $this->filename(),
            'variants' => $variants,
        ];
    }

    /**
     * A ready-made srcset string, smallest first.
     *
     * Empty when no variants exist, so a caller can fall back to the original.
     */
    public function srcset(string $baseUrl = '/api/media/file'): string
    {
        $urls = $this->urls($baseUrl)['variants'];

        $parts = [];
        foreach (ImageSize::ladder() as $size) {
            if (isset($urls[$size->value])) {
                $parts[] = $urls[$size->value]['url'] . ' ' . $size->width() . 'w';
            }
        }

        return implode(', ', $parts);
    }

    /**
     * How well this image will hold up, optionally for a slot of a known width.
     *
     * Null for anything without pixels to count — a non-image, or a file whose
     * dimensions could not be read. Silence is better than a verdict derived
     * from a width nobody measured.
     */
    public function quality(?int $displayWidth = null): ?ImageQuality
    {
        if (!$this->isImage() || $this->width === null || $this->width <= 0) {
            return null;
        }

        return $displayWidth !== null && $displayWidth > 0
            ? ImageQuality::forSlot($this->width, $displayWidth)
            : ImageQuality::forUpload($this->width);
    }

    public function withAlt(string $alt): self
    {
        return new self(
            $this->id, $this->extension, $this->mimeType, $this->originalName,
            $this->bytes, $this->width, $this->height, $this->variants,
            $alt, $this->uploadedAt,
        );
    }

    /**
     * @param ?int $displayWidth The width a field displays this image at, when
     *                           the caller knows it. Given one, `quality` is
     *                           answered for that slot rather than in general.
     *
     * @return array<string, mixed>
     */
    public function toArray(?int $displayWidth = null): array
    {
        $quality = $this->quality($displayWidth);

        return [
            'id' => $this->id,
            'extension' => $this->extension,
            'mimeType' => $this->mimeType,
            'originalName' => $this->originalName,
            'bytes' => $this->bytes,
            'width' => $this->width,
            'height' => $this->height,
            'variants' => array_map(static fn (ImageSize $s): string => $s->value, $this->variants),
            'alt' => $this->alt,
            'uploadedAt' => $this->uploadedAt,
            'urls' => $this->urls(),
            'srcset' => $this->srcset(),
            // Part of the payload rather than only the admin UI, so any client
            // reading media can tell an editor what the ladder could not do.
            'quality' => $quality?->toArray(),
        ];
    }
}
