<?php

declare(strict_types=1);

namespace Click\Cms\Domain\Media;

use InvalidArgumentException;

/**
 * One item in the media library.
 *
 * `id` is the stable reference stored in content. It is generated by the CMS
 * rather than taken from the upload, so a page never depends on whatever a
 * browser happened to call the file, and two people uploading "photo.jpg"
 * cannot collide.
 *
 * The original filename is kept for display only.
 */
final class MediaItem
{
    /**
     * @param list<ImageSize> $variants Sizes actually generated for this item.
     */
    private function __construct(
        public readonly string $id,
        public readonly string $extension,
        public readonly string $mimeType,
        public readonly string $originalName,
        public readonly int $bytes,
        public readonly ?int $width,
        public readonly ?int $height,
        public readonly array $variants,
        public readonly string $alt,
        public readonly string $uploadedAt,
        public readonly FocalPoint $focalPoint,
        // Side length in pixels of the focal-point-centred square crop, or null
        // when none exists — a resolution-independent SVG never has one, and a
        // raster only gains one once the processor could produce it.
        public readonly ?int $squareCrop,
        // Art-directed fixed-box crops the site declared, by name, each with the
        // pixel dimensions actually produced: `['wide' => ['width' => 1200,
        // 'height' => 675]]`. Empty when the site declares none, or for an SVG.
        // Focal-point-centred like the square, and recut when the point moves.
        public readonly array $crops = [],
    ) {}

    /**
     * @param list<ImageSize> $variants
     */
    public static function create(
        string $id,
        string $extension,
        string $mimeType,
        string $originalName,
        int $bytes,
        ?int $width = null,
        ?int $height = null,
        array $variants = [],
        string $alt = '',
        ?string $uploadedAt = null,
        ?FocalPoint $focalPoint = null,
        ?int $squareCrop = null,
        array $crops = [],
    ): self {
        if (preg_match('/^[a-z0-9][a-z0-9-]*$/', $id) !== 1) {
            throw new InvalidArgumentException(
                'Media id must be lowercase letters, digits and dashes.'
            );
        }

        // Checked against the accepted set rather than merely for shape: "php"
        // is a well-formed lowercase extension, and a stored filename ending in
        // it should never be constructible even though media lives outside the
        // document root.
        if (!in_array($extension, UploadPolicy::acceptedExtensions(), true)) {
            throw new InvalidArgumentException(
                "Media extension \"{$extension}\" is not an accepted image type."
            );
        }

        return new self(
            id: $id,
            extension: $extension,
            mimeType: $mimeType,
            originalName: $originalName,
            bytes: $bytes,
            width: $width,
            height: $height,
            variants: $variants,
            alt: $alt,
            uploadedAt: $uploadedAt ?? gmdate('c'),
            focalPoint: $focalPoint ?? FocalPoint::center(),
            squareCrop: $squareCrop !== null && $squareCrop > 0 ? $squareCrop : null,
            crops: self::normaliseCrops($crops),
        );
    }

    /**
     * Keep only well-formed crop entries: a slug name mapping to positive
     * width/height. A stored file written before crops existed, or a malformed
     * one, simply contributes nothing rather than a broken URL.
     *
     * @param  mixed $crops
     * @return array<string, array{width: int, height: int}>
     */
    private static function normaliseCrops(mixed $crops): array
    {
        if (!is_array($crops)) {
            return [];
        }

        $out = [];
        foreach ($crops as $name => $dims) {
            if (!is_string($name) || preg_match('/^[a-z0-9][a-z0-9-]*$/', $name) !== 1) {
                continue;
            }
            if (!is_array($dims)) {
                continue;
            }
            $width = (int) ($dims['width'] ?? 0);
            $height = (int) ($dims['height'] ?? 0);
            if ($width > 0 && $height > 0) {
                $out[$name] = ['width' => $width, 'height' => $height];
            }
        }

        return $out;
    }

    /**
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        $variants = [];
        foreach ((array) ($row['variants'] ?? []) as $value) {
            $size = ImageSize::tryFrom((string) $value);
            if ($size !== null) {
                $variants[] = $size;
            }
        }

        return self::create(
            id: (string) ($row['id'] ?? ''),
            extension: (string) ($row['extension'] ?? ''),
            mimeType: (string) ($row['mimeType'] ?? 'application/octet-stream'),
            originalName: (string) ($row['originalName'] ?? ''),
            bytes: (int) ($row['bytes'] ?? 0),
            width: isset($row['width']) ? (int) $row['width'] : null,
            height: isset($row['height']) ? (int) $row['height'] : null,
            variants: $variants,
            alt: (string) ($row['alt'] ?? ''),
            uploadedAt: isset($row['uploadedAt']) ? (string) $row['uploadedAt'] : null,
            focalPoint: FocalPoint::fromArray(
                is_array($row['focalPoint'] ?? null) ? $row['focalPoint'] : []
            ),
            squareCrop: isset($row['squareCrop']) ? (int) $row['squareCrop'] : null,
            crops: is_array($row['crops'] ?? null) ? $row['crops'] : [],
        );
    }

    public function filename(): string
    {
        return $this->id . '.' . $this->extension;
    }

    /**
     * The stored name of the square crop, or null when there is none. Named off
     * the same id as every other file so the serving path resolves it with the
     * one rule it already uses.
     */
    public function squareCropFilename(): ?string
    {
        return $this->squareCrop === null
            ? null
            : $this->id . '-square.' . $this->extension;
    }

    /**
     * The stored name of a named art-directed crop, following the same id-based
     * rule the serving path already resolves. Null when the crop was not
     * produced for this item.
     */
    public function cropFilename(string $name): ?string
    {
        return isset($this->crops[$name])
            ? $this->id . '-crop-' . $name . '.' . $this->extension
            : null;
    }

    public function isImage(): bool
    {
        return str_starts_with($this->mimeType, 'image/');
    }

    /**
     * What this item is, in the vocabulary a field picker asks in: `image` or
     * `video`.
     *
     * The two are not interchangeable in any slot. An image field wants a
     * picture and a file field wants a clip, and before this existed neither
     * could say so — every picker listed the whole library, which put videos in
     * the image chooser with a broken thumbnail and made them selectable into a
     * field that renders an `<img>`.
     *
     * Derived from the mime type rather than stored, because the mime type is
     * what upload already decided and a second copy could disagree with it.
     */
    public function kind(): string
    {
        return $this->isImage() ? 'image' : 'video';
    }

    /**
     * Public URLs for the original and every generated variant.
     *
     * Returned as data rather than built in a template so a front end can put
     * the variants straight into a srcset without knowing the naming rule.
     *
     * The `square` key is present only when a focal-point crop exists, so a
     * caller can test for it rather than for a zero.
     *
     * @return array{original: string, variants: array<string, array{url: string, width: int}>, square?: array{url: string, width: int, height: int}}
     */
    public function urls(string $baseUrl = '/api/media/file'): array
    {
        $base = rtrim($baseUrl, '/');

        $variants = [];
        foreach ($this->variants as $size) {
            $variants[$size->value] = [
                'url' => $base . '/' . $size->filenameFor($this->id, $this->extension),
                'width' => $size->width(),
            ];
        }

        $urls = [
            'original' => $base . '/' . $this->filename(),
            'variants' => $variants,
        ];

        $square = $this->squareCropFilename();
        if ($square !== null) {
            // A square is as wide as it is tall, so both are the stored side.
            $urls['square'] = [
                'url' => $base . '/' . $square,
                'width' => $this->squareCrop,
                'height' => $this->squareCrop,
            ];
        }

        // Named art-directed crops, each with the box it was cut to, so a front
        // end drops the right one into an <img> without knowing the naming rule.
        if ($this->crops !== []) {
            $crops = [];
            foreach ($this->crops as $name => $dims) {
                $crops[$name] = [
                    'url' => $base . '/' . $this->cropFilename($name),
                    'width' => $dims['width'],
                    'height' => $dims['height'],
                ];
            }
            $urls['crops'] = $crops;
        }

        return $urls;
    }

    /**
     * A ready-made srcset string, smallest first.
     *
     * Empty when no variants exist, so a caller can fall back to the original.
     */
    public function srcset(string $baseUrl = '/api/media/file'): string
    {
        $urls = $this->urls($baseUrl)['variants'];

        $parts = [];
        foreach (ImageSize::ladder() as $size) {
            if (isset($urls[$size->value])) {
                $parts[] = $urls[$size->value]['url'] . ' ' . $size->width() . 'w';
            }
        }

        return implode(', ', $parts);
    }

    /**
     * How well this image will hold up, optionally for a slot of a known width.
     *
     * Null for anything without pixels to count — a non-image, or a file whose
     * dimensions could not be read. Silence is better than a verdict derived
     * from a width nobody measured.
     */
    public function quality(?int $displayWidth = null): ?ImageQuality
    {
        if (!$this->isImage() || $this->width === null || $this->width <= 0) {
            return null;
        }

        return $displayWidth !== null && $displayWidth > 0
            ? ImageQuality::forSlot($this->width, $displayWidth)
            : ImageQuality::forUpload($this->width);
    }

    public function withAlt(string $alt): self
    {
        return new self(
            $this->id, $this->extension, $this->mimeType, $this->originalName,
            $this->bytes, $this->width, $this->height, $this->variants,
            $alt, $this->uploadedAt, $this->focalPoint, $this->squareCrop,
            $this->crops,
        );
    }

    public function withFocalPoint(FocalPoint $focalPoint): self
    {
        return new self(
            $this->id, $this->extension, $this->mimeType, $this->originalName,
            $this->bytes, $this->width, $this->height, $this->variants,
            $this->alt, $this->uploadedAt, $focalPoint, $this->squareCrop,
            $this->crops,
        );
    }

    /**
     * Record (or clear) the side length of the focal-point square crop.
     *
     * A crop is regenerated whenever the focal point moves, so this is set right
     * after `withFocalPoint`; passing null when the processor could not produce
     * one keeps the payload honest rather than pointing at a file that is not
     * there.
     */
    public function withSquareCrop(?int $squareCrop): self
    {
        return new self(
            $this->id, $this->extension, $this->mimeType, $this->originalName,
            $this->bytes, $this->width, $this->height, $this->variants,
            $this->alt, $this->uploadedAt, $this->focalPoint,
            $squareCrop !== null && $squareCrop > 0 ? $squareCrop : null,
            $this->crops,
        );
    }

    /**
     * Record (or clear) the art-directed crops produced for this item. Set right
     * after the focal point moves, alongside the square, so the stored boxes
     * always match the point last marked; a malformed entry is dropped.
     *
     * @param array<string, array{width: int, height: int}> $crops
     */
    public function withCrops(array $crops): self
    {
        return new self(
            $this->id, $this->extension, $this->mimeType, $this->originalName,
            $this->bytes, $this->width, $this->height, $this->variants,
            $this->alt, $this->uploadedAt, $this->focalPoint, $this->squareCrop,
            self::normaliseCrops($crops),
        );
    }

    /**
     * @param ?int $displayWidth The width a field displays this image at, when
     *                           the caller knows it. Given one, `quality` is
     *                           answered for that slot rather than in general.
     *
     * @return array<string, mixed>
     */
    public function toArray(?int $displayWidth = null): array
    {
        $quality = $this->quality($displayWidth);

        return [
            'id' => $this->id,
            'extension' => $this->extension,
            'mimeType' => $this->mimeType,
            'originalName' => $this->originalName,
            'bytes' => $this->bytes,
            'width' => $this->width,
            'height' => $this->height,
            'variants' => array_map(static fn (ImageSize $s): string => $s->value, $this->variants),
            'alt' => $this->alt,
            'uploadedAt' => $this->uploadedAt,
            // Side of the focal-point square crop, null when there is none. A
            // front end needing a fixed box reads urls.square; this is the plain
            // number beside it.
            'squareCrop' => $this->squareCrop,
            // The named crops and their boxes, mirroring squareCrop: the plain
            // dimensions beside the ready-made URLs in urls.crops.
            'crops' => $this->crops,
            'urls' => $this->urls(),
            'srcset' => $this->srcset(),
            // The mark itself, plus a ready-made CSS value so a front end that
            // crops with object-fit keeps the subject visible without knowing
            // the fraction convention. Both ride along in the existing payload,
            // so the renderer and delivery API carry it for free.
            'focalPoint' => $this->focalPoint->toArray(),
            'objectPosition' => $this->focalPoint->toCss(),
            // Part of the payload rather than only the admin UI, so any client
            // reading media can tell an editor what the ladder could not do.
            'quality' => $quality?->toArray(),
        ];
    }
}
