<?php

declare(strict_types=1);

namespace Click\Cms\Domain\Media;

/**
 * What the media library will accept.
 *
 * Decisions worth stating, because file upload is the most attacked part of a
 * CMS:
 *
 *  - Types are decided by the file's actual content, never by its name. An
 *    extension is attacker-controlled and proves nothing.
 *
 *  - SVG is refused. It is an XML document that may contain script, so serving
 *    one inline is a cross-site scripting hole. Refusing it is a real cost —
 *    logos are usually SVG — but allowing it safely needs a sanitiser, and a
 *    half-sanitised SVG is worse than none.
 *
 *  - Stored names are generated by the CMS. Nothing an uploader chooses ever
 *    becomes part of a path.
 */
final class UploadPolicy
{
    public const MAX_BYTES = 10 * 1024 * 1024;

    /**
     * MIME type => canonical extension. Anything absent is refused.
     *
     * Deliberately narrow: these are the types the library can inspect, resize
     * and serve with confidence.
     */
    private const ACCEPTED = [
        'image/jpeg' => 'jpg',
        'image/png' => 'png',
        'image/gif' => 'gif',
        'image/webp' => 'webp',
    ];

    /**
     * Types that are refused with a specific explanation rather than a generic
     * one, because the reason is not obvious to whoever is uploading.
     */
    private const EXPLAINED_REFUSALS = [
        'image/svg+xml' => 'SVG cannot be accepted because it can contain scripts.',
        'text/html' => 'HTML cannot be accepted.',
        'application/x-php' => 'Executable files cannot be accepted.',
    ];

    public static function isAccepted(string $mimeType): bool
    {
        return isset(self::ACCEPTED[$mimeType]);
    }

    public static function extensionFor(string $mimeType): ?string
    {
        return self::ACCEPTED[$mimeType] ?? null;
    }

    /**
     * @return list<string>
     */
    public static function acceptedMimeTypes(): array
    {
        return array_keys(self::ACCEPTED);
    }

    /**
     * The only extensions a stored file may ever carry.
     *
     * @return list<string>
     */
    public static function acceptedExtensions(): array
    {
        return array_values(array_unique(array_values(self::ACCEPTED)));
    }

    /** A human explanation of why a type was refused. */
    public static function refusalReason(string $mimeType): string
    {
        return self::EXPLAINED_REFUSALS[$mimeType]
            ?? 'Only JPEG, PNG, GIF and WebP images can be uploaded.';
    }

    /**
     * Turn a display name into a slug used for the stored filename.
     *
     * The result is only ever a hint for humans — it is combined with a random
     * suffix by the caller, so a collision or an empty result is harmless.
     */
    public static function slugFor(string $originalName): string
    {
        $stem = pathinfo($originalName, PATHINFO_FILENAME);

        $slug = strtolower($stem);
        $slug = preg_replace('/[^a-z0-9]+/', '-', $slug) ?? '';
        $slug = trim($slug, '-');
        $slug = preg_replace('/-{2,}/', '-', $slug) ?? '';

        // Long names make unwieldy paths and reveal more than needed about the
        // uploader's filesystem.
        $slug = substr($slug, 0, 40);
        $slug = trim($slug, '-');

        return $slug === '' ? 'image' : $slug;
    }
}
