<?php

declare(strict_types=1);

namespace Click\Cms\Domain\Media;

/**
 * What the media library will accept.
 *
 * Decisions worth stating, because file upload is the most attacked part of a
 * CMS:
 *
 *  - Types are decided by the file's actual content, never by its name. An
 *    extension is attacker-controlled and proves nothing.
 *
 *  - SVG is accepted, but only through sanitisation. Unlike a raster it is an
 *    XML document a browser executes when served inline, so a `<script>` or an
 *    `onload=` in one is a stored cross-site-scripting hole. SVG stayed refused
 *    for exactly that reason until there was a sanitiser to lean on. Now the
 *    type is allowed, but MediaService stores the *sanitised* bytes and refuses
 *    an SVG that cannot be cleaned — the raw upload is never trusted or kept.
 *    Logos are usually SVG, so this is a cost worth paying once it can be paid
 *    safely.
 *
 *  - Stored names are generated by the CMS. Nothing an uploader chooses ever
 *    becomes part of a path.
 */
final class UploadPolicy
{
    public const MAX_BYTES = 10 * 1024 * 1024;

    /**
     * MIME type => canonical extension. Anything absent is refused.
     *
     * The four rasters are inspected, resized and served directly. SVG is here
     * too, but its acceptance is conditional in a way a flat map cannot express:
     * MediaService only stores an SVG whose bytes pass SvgSanitizer, and stores
     * the sanitiser's output rather than the upload. Listing it here is what lets
     * that sanitised result carry a `.svg` name and be served — the type gate,
     * not a promise the raw file is safe.
     */
    private const ACCEPTED = [
        'image/jpeg' => 'jpg',
        'image/png' => 'png',
        'image/gif' => 'gif',
        'image/webp' => 'webp',
        'image/svg+xml' => 'svg',
    ];

    /**
     * Types that are refused with a specific explanation rather than a generic
     * one, because the reason is not obvious to whoever is uploading.
     */
    private const EXPLAINED_REFUSALS = [
        'text/html' => 'HTML cannot be accepted.',
        'application/x-php' => 'Executable files cannot be accepted.',
    ];

    public static function isAccepted(string $mimeType): bool
    {
        return isset(self::ACCEPTED[$mimeType]);
    }

    public static function extensionFor(string $mimeType): ?string
    {
        return self::ACCEPTED[$mimeType] ?? null;
    }

    /**
     * @return list<string>
     */
    public static function acceptedMimeTypes(): array
    {
        return array_keys(self::ACCEPTED);
    }

    /**
     * The only extensions a stored file may ever carry.
     *
     * @return list<string>
     */
    public static function acceptedExtensions(): array
    {
        return array_values(array_unique(array_values(self::ACCEPTED)));
    }

    /** A human explanation of why a type was refused. */
    public static function refusalReason(string $mimeType): string
    {
        return self::EXPLAINED_REFUSALS[$mimeType]
            ?? 'Only JPEG, PNG, GIF, WebP and SVG images can be uploaded.';
    }

    /**
     * Why an SVG that was the right *type* was still not stored.
     *
     * An SVG is accepted only once its bytes sanitise; one that cannot be made
     * safe is refused rather than stored raw, and the reason names the XSS risk
     * so the uploader understands it is not an arbitrary rejection.
     */
    public static function svgRefusalReason(): string
    {
        return 'This SVG could not be made safe to display — it contains script '
            . 'or external references that cannot be removed without breaking it — '
            . 'so it was not stored.';
    }

    /**
     * Turn a display name into a slug used for the stored filename.
     *
     * The result is only ever a hint for humans — it is combined with a random
     * suffix by the caller, so a collision or an empty result is harmless.
     */
    public static function slugFor(string $originalName): string
    {
        $stem = pathinfo($originalName, PATHINFO_FILENAME);

        $slug = strtolower($stem);
        $slug = preg_replace('/[^a-z0-9]+/', '-', $slug) ?? '';
        $slug = trim($slug, '-');
        $slug = preg_replace('/-{2,}/', '-', $slug) ?? '';

        // Long names make unwieldy paths and reveal more than needed about the
        // uploader's filesystem.
        $slug = substr($slug, 0, 40);
        $slug = trim($slug, '-');

        return $slug === '' ? 'image' : $slug;
    }
}
