<?php

declare(strict_types=1);

namespace Click\Cms\Application\Collection;

use Click\Cms\Domain\Collection\CollectionType;
use Click\Cms\Domain\Collection\CollectionTypeRepository;
use Click\Cms\Domain\ValueObjects\Locale;

/**
 * The two directions of a collection entry's public address: a request path in,
 * and an href out.
 *
 * Both live here on purpose. A listing that built `/blog/x` one way while the
 * router matched `/blog/x` another way is a site full of links to its own 404s,
 * and that divergence is invisible until someone clicks. One class owns the
 * mapping, so the link and the route cannot disagree.
 *
 * ## What this deliberately does not decide
 *
 * Whether the entry exists, and whether it is published. This resolves a path to
 * *the address of an entry*, nothing more — the caller reads the published
 * document (or fails to) and 404s. Keeping publication out of here is what makes
 * it impossible for a routing change to become a disclosure: there is no read of
 * a draft to accidentally serve.
 *
 * ## Language
 *
 * Routes are not translated. `/de/blog/x` is the German entry `x` and `/blog/x`
 * the default-language one, exactly as pages work: the language prefix is split
 * off before a path reaches {@see match()}, and put back by {@see hrefFor()}. A
 * site that wants `/de/blog` to read `/de/journal` is asking for per-language
 * routes, which nothing here pretends to offer.
 *
 * One consequence worth stating: a collection routed at a segment that spells a
 * *configured* language — `route: "de"` on a site that offers German — is
 * unreachable, because the language prefix is decided first and wins. That is a
 * site misconfiguration this class cannot see (it does not know the site's
 * languages) and would be wrong to guess at, since `route: "de"` is perfectly
 * good on a site that offers no German.
 */
final class EntryRouter
{
    /**
     * The shape an entry slug may have in a URL.
     *
     * Slugs are generated by {@see CollectionService::create()}, which lowercases
     * and dashes everything, so this is deliberately narrower than what storage
     * would accept. Starting and ending on an alphanumeric is what excludes `.`
     * and `..` outright: refusing a suspicious path here turns the whole class of
     * traversal attempt into "no such address" before a key is ever built, rather
     * than trusting a layer further down to notice — the same discipline the
     * preview route applies to a page slug.
     */
    private const SLUG_PATTERN = '/^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$/D';

    public function __construct(private readonly CollectionTypeRepository $types) {}

    /**
     * Resolve a public path — already stripped of any language prefix, with no
     * leading or trailing slash — to the entry it addresses, or null.
     *
     * Null means "this path is not an entry address", which is the answer for a
     * path under no declared route, for a bare route (`blog`, which is a listing
     * page's job, not an entry's), and for anything deeper than route + slug.
     */
    public function match(string $path): ?EntryAddress
    {
        $path = trim($path, '/');
        if ($path === '' || !str_contains($path, '/')) {
            // No route can match without at least one segment after it, so a
            // single-segment path is never an entry — which is exactly what keeps
            // a *page* whose slug happens to equal a route reachable.
            return null;
        }

        foreach ($this->routedTypes() as $type) {
            $prefix = $type->route . '/';
            if (!str_starts_with($path, $prefix)) {
                continue;
            }

            $slug = substr($path, strlen($prefix));
            if (preg_match(self::SLUG_PATTERN, $slug) !== 1) {
                // Either an unsafe slug or a deeper path — `blog/2025/x` names no
                // entry, and treating its first segment as one would invent an
                // address the site never declared.
                return null;
            }

            return new EntryAddress($type, $slug);
        }

        return null;
    }

    /**
     * The href for one entry: `/blog/x`, or `/de/blog/x` when it is being served
     * in a language other than the site's default. Null when the collection has
     * no public address, which is how a listing knows to render an entry as plain
     * text rather than a link to nowhere.
     *
     * The default language carries no prefix, matching how pages and menus build
     * their own hrefs — two spellings of one address would split the render cache
     * and confuse every canonical URL on the site.
     */
    public function hrefFor(CollectionType $type, string $slug, Locale $locale, Locale $defaultLocale): ?string
    {
        $path = $type->pathFor($slug);
        if ($path === null) {
            return null;
        }

        return $locale->equals($defaultLocale)
            ? '/' . $path
            : '/' . $locale->code . '/' . $path;
    }

    /**
     * Collections that declare a route, longest route first.
     *
     * Longest first so `journal/notes` is tested before `journal` and therefore
     * wins the paths it was declared for; shortest-first would let the broader
     * route swallow them. Two collections declaring the *same* route is a site
     * error with no right answer, so the first as the repository orders them — by
     * filename, deterministically — takes it, and the other is simply not
     * reachable. Deciding it here rather than in the loader keeps the loader's
     * contract ("one file, one type") intact.
     *
     * @return list<CollectionType>
     */
    public function routedTypes(): array
    {
        $routed = array_values(array_filter(
            $this->types->all(),
            static fn (CollectionType $type): bool => $type->hasPublicAddress(),
        ));

        usort(
            $routed,
            static fn (CollectionType $a, CollectionType $b): int
                => strlen($b->route) <=> strlen($a->route),
        );

        return $routed;
    }
}
